

 </div> <!-- / main container -->
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="<?php echo $config->urls->templates?>js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="<?php echo $config->urls->templates?>js/bootstrap.min.js"></script>

  </body>
</html>